#!/usr/bin/env python3
"""Generate PNG (and optionally WebP) previews for every asset.

Previews are build artifacts: they are written to previews/ (gitignored) and
regenerated by CI or release builds. The SVG remains the canonical source.

Usage:
    python scripts/generate_previews.py                 # PNG 512px
    python scripts/generate_previews.py --size 1024     # PNG 1024px
    python scripts/generate_previews.py --format png --format webp
    python scripts/generate_previews.py --no-clean      # keep stale files
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets"
PREVIEWS = ROOT / "previews"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--size", type=int, default=512)
    parser.add_argument("--format", action="append", default=["png"], choices=["png", "webp"])
    parser.add_argument("--no-clean", action="store_true", help="keep stale previews")
    args = parser.parse_args()

    try:
        import cairosvg  # type: ignore
    except ImportError:
        print("cairosvg is not installed; skipping preview generation.")
        print("Install it with: pip install cairosvg")
        return 0

    from PIL import Image  # type: ignore

    svgs = sorted(ASSETS.rglob("*.svg"))
    if not args.no_clean:
        for old in PREVIEWS.glob("**/*"):
            if old.is_file() and old.suffix in (".png", ".webp"):
                old.unlink()

    count = 0
    for svg in svgs:
        rel = svg.relative_to(ASSETS)
        stem = rel.with_suffix("")
        png_path = PREVIEWS / f"{stem}.png"
        png_path.parent.mkdir(parents=True, exist_ok=True)
        cairosvg.svg2png(url=str(svg), write_to=str(png_path), output_width=args.size)
        count += 1
        if "webp" in args.format:
            img = Image.open(png_path).convert("RGBA")
            webp_path = PREVIEWS / f"{stem}.webp"
            img.save(webp_path, "WEBP", quality=88, method=6)
            img.close()

    print(f"Generated {count} previews in {PREVIEWS.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
